### ISSUE TITLE
Bug: Item name with colon

### ISSUE THREAD

**Issue by kravlost** [TommyX12/VIR#4]
I can enter an item name with a colon, but when I click on Save, VIR says that the item name is invalid. I cannot then edit the item name, and have to quit and restart VIR to add a new item with a different name.

**Comment by TommyX12** [comment]
Hi there, I was unable to reproduce the issue you mentioned. I tried adding/editing an item and entering a name with a colon, but everything still worked fine afterwards. Could you please specify the exact steps to trigger the problem?

**Comment by kravlost** [comment]
I am using the pre-built binary for Windows. If I add an item and include a colon in the item name, when I click on Save VIR says that the item name is invalid. When I try to edit the item name, VIR doesn't let me. I know that's pretty much what I wrote before, but I'm not sure how else to describe it
